"""
Django settings for IXEDU project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKEND_DIR = os.path.join(BASE_DIR, 'backend')
AUTH_DIR = os.path.join(BASE_DIR, 'authentication')
FORUM_DIR = os.path.join(BASE_DIR, 'forum')
SE_DIR = os.path.join(BASE_DIR, 'searchengine')
UNI_DIR = os.path.join(BASE_DIR, 'university')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+^k8_ke1-yfm4ziba8%r!(a!^fgu5i@yo+oay)!pe%12g65dz4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['.ixedu.org']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'backend',
    'forum',
    'searchengine',
    'university'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'IXEDU.urls'

LOGIN_URL = "/login"
LOGIN_REDIRECT_URL = '/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 os.path.join(AUTH_DIR, 'templates'),
                 os.path.join(FORUM_DIR, 'templates'),
                 os.path.join(UNI_DIR, 'templates'),
                 os.path.join(SE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.media',
                'django.core.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'IXEDU.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

if not DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django_postgrespool',
            'NAME': 'ddslv04a0i165s',
            'USER': 'fddhpptxlggkop',
            'PASSWORD': 'm37_OAxiSlVuNe5G-qnCl3zXRS',
            'HOST': 'ec2-54-83-22-48.compute-1.amazonaws.com',
            'PORT': '5432'
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django_postgrespool',
            'NAME': 'da88u4s7mk0uta',
            'USER': 'bqwzkkuirdtbkw',
            'PASSWORD': 'tmVOsitKx-l13uowFIKbH6pubR',
            'HOST': 'ec2-54-243-220-140.compute-1.amazonaws.com',
            'PORT': '5432'
        }
    }


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    os.path.join(AUTH_DIR, 'static'),
    os.path.join(FORUM_DIR, 'static'),
    os.path.join(SE_DIR, 'static'),
    os.path.join(UNI_DIR, 'static')
)

AWS_ACCESS_KEY_ID = 'AKIAJG46VBV7P4GN4N5A'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'ixedu'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
STATICFILES_LOCATION = 'static'

if not DEBUG:
    STATICFILES_STORAGE = 'IXEDU.storage.StaticStorage'
    STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, STATICFILES_LOCATION)
else:
    STATIC_URL = "/static/"

MEDIAFILES_LOCATION = 'media'
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
DEFAULT_FILE_STORAGE = 'IXEDU.storage.MediaStorage'

EMAIL_HOST = 'mail.privateemail.com'
EMAIL_HOST_USER = 'team@ixedu.org'
EMAIL_HOST_PASSWORD = 'carnegiemellonuniversity'
EMAIL_PORT = 14
EMAIL_USE_TLS = True





