# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_filledsubcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiles',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
