# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20160409_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
