# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_university_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_user',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(default='Cut and Shoot', max_length=80),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.FileField(default='uni_logos/default_univ.jpg', upload_to='uni_logos/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='phone_number',
            field=models.CharField(blank=True, default='No phone number', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='state',
            field=models.CharField(default='TX', max_length=80),
        ),
    ]
