# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20160520_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
    ]
