# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20160520_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiles',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
