# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_unifiles_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ordering',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
