# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_customuser_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiles',
            name='ordering',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
