# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_unifiles_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniSizeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
