# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_unisizegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='size_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unis', to='backend.UniSizeGroup'),
        ),
    ]
