# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_university_size_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='profile_thumbnails/'),
        ),
        migrations.AddField(
            model_name='unifiles',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='uni_thumbnails/'),
        ),
    ]
