# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20160629_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='population',
            new_name='grad',
        ),
        migrations.AddField(
            model_name='university',
            name='program_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='university',
            name='undergrad',
            field=models.IntegerField(default=0),
        ),
    ]
